# Generated by Django 3.1.4 on 2020-12-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonu', models.CharField(blank=True, max_length=100, null=True)),
                ('sinifi', models.CharField(blank=True, max_length=100, null=True)),
                ('numarasi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ilkapp',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
