# Generated by Django 3.1.4 on 2020-12-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
