# Generated by Django 3.1.4 on 2020-12-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0005_ogrencikayit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencikayit',
            name='portfolio_site',
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='numarasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='sinifi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='telefonu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
