# Generated by Django 3.1.4 on 2020-12-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0006_auto_20201218_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencikayit',
            name='user',
        ),
    ]
