# Generated by Django 3.1.4 on 2020-12-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0007_remove_ogrencikayit_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ogrenci',
        ),
    ]
