# Generated by Django 3.1.4 on 2020-12-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0009_auto_20201219_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrencikayit',
            name='numarasi',
        ),
    ]
