# Generated by Django 3.1.4 on 2020-12-19 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0010_remove_ogrencikayit_numarasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=11, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonu', models.CharField(blank=True, max_length=15, null=True)),
                ('adres', models.CharField(blank=True, max_length=100, null=True)),
                ('ili', models.CharField(blank=True, max_length=100, null=True)),
                ('ilcesi', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='logo')),
                ('kayittarihi', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='ogrencikurum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
