# Generated by Django 3.1.4 on 2020-12-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0011_auto_20201220_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurum',
            name='vergidairesi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kurum',
            name='verginumarası',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
