# Generated by Django 3.1.4 on 2020-12-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0012_auto_20201220_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurum',
            old_name='verginumarası',
            new_name='verginumarasi',
        ),
    ]
