# Generated by Django 3.1.4 on 2020-12-20 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0013_auto_20201220_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ogretmenKayit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=11, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonu', models.CharField(blank=True, max_length=15, null=True)),
                ('adres', models.CharField(blank=True, max_length=10, null=True)),
                ('bransi', models.CharField(blank=True, max_length=100, null=True)),
                ('yanbransi', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=100, null=True)),
                ('kayittarihi', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('ogretmenkurum', models.CharField(blank=True, max_length=100, null=True)),
                ('idareci', models.BooleanField(default=False)),
            ],
        ),
    ]
