# Generated by Django 3.1.4 on 2020-12-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0014_ogretmenkayit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrencikayit',
            old_name='ogrencikurum',
            new_name='kurum',
        ),
        migrations.RenameField(
            model_name='ogretmenkayit',
            old_name='ogretmenkurum',
            new_name='kurum',
        ),
    ]
