# Generated by Django 3.1.4 on 2020-12-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0016_auto_20201220_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurum',
            name='kayittarihi',
        ),
        migrations.RemoveField(
            model_name='ogrencikayit',
            name='kayittarihi',
        ),
        migrations.RemoveField(
            model_name='ogrencikayit',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='ogretmenkayit',
            name='kayittarihi',
        ),
        migrations.RemoveField(
            model_name='ogretmenkayit',
            name='nim',
        ),
    ]
