# Generated by Django 3.1.4 on 2020-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0017_auto_20201220_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencikayit',
            name='ksinifi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
