# Generated by Django 3.1.4 on 2020-12-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0018_ogrencikayit_ksinifi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ksinifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ksinifi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ogrencikayit',
            name='ksinifi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
