# Generated by Django 3.1.4 on 2020-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0019_auto_20201220_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='dersler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dersadi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
