# Generated by Django 3.1.4 on 2020-12-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0020_dersler'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogretmenkayit',
            name='birebirsaati',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
