# Generated by Django 3.1.4 on 2020-12-23 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0021_ogretmenkayit_birebirsaati'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogretmenkayit',
            name='birebirzamani',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='ogretmenkayit',
            name='birebirsaati',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
