# Generated by Django 3.1.4 on 2020-12-23 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0022_auto_20201224_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='birebir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bbdersadi', models.CharField(blank=True, max_length=100, null=True)),
                ('bbogrenci', models.CharField(blank=True, max_length=100, null=True)),
                ('bbogretmen', models.CharField(blank=True, max_length=100, null=True)),
                ('bbtarihi', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('bbsaati', models.CharField(blank=True, max_length=100, null=True)),
                ('bbonay', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='ogretmenkayit',
            name='birebirzamani',
        ),
    ]
