# Generated by Django 3.1.4 on 2020-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0024_auto_20201224_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='birebir',
            name='bbogrenciid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='birebir',
            name='bbogretmenid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
