# Generated by Django 3.1.4 on 2020-12-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0025_auto_20201226_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='hafta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gunler', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
