# Generated by Django 3.1.4 on 2020-12-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0029_auto_20201227_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birebir',
            name='bbgunu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
