# Generated by Django 3.1.4 on 2020-12-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0030_auto_20201227_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='birebir',
            name='bbgun',
            field=models.PositiveSmallIntegerField(blank=True, max_length=1, null=True),
        ),
    ]
