# Generated by Django 3.1.4 on 2020-12-28 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0033_birebir_bbgun'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesajlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gonderen', models.CharField(blank=True, max_length=100, null=True)),
                ('alici', models.CharField(blank=True, max_length=100, null=True)),
                ('mesaj', models.TextField(blank=True, max_length=1000, null=True)),
                ('baslik', models.CharField(blank=True, max_length=100, null=True)),
                ('resim', models.ImageField(blank=True, upload_to='mesajimg')),
                ('tarih', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('okundu', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='birebir',
            name='bbgun',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
