# Generated by Django 3.1.4 on 2020-12-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0035_auto_20201229_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurum',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logom'),
        ),
        migrations.AlterField(
            model_name='mesajlar',
            name='resim',
            field=models.ImageField(blank=True, upload_to='mesajfile'),
        ),
    ]
