# Generated by Django 3.1.4 on 2021-01-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0038_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
