# Generated by Django 3.1.4 on 2021-01-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0040_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='birebir',
            name='bbbitissaati',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birebir',
            name='bbsaati',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
