# Generated by Django 3.1.4 on 2021-01-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0041_auto_20210102_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birebir',
            name='bbbitissaati',
        ),
        migrations.AlterField(
            model_name='birebir',
            name='bbsaati',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
