# Generated by Django 3.1.4 on 2021-01-02 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0042_auto_20210102_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dgonderen', models.CharField(blank=True, max_length=100, null=True)),
                ('duyuru', models.TextField(blank=True, max_length=1000, null=True)),
                ('dbaslik', models.CharField(blank=True, max_length=100, null=True)),
                ('dogretmen', models.BooleanField(default=False)),
                ('dogrenci', models.BooleanField(default=False)),
                ('dtarih', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
