# Generated by Django 3.1.4 on 2021-01-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0043_duyurular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurum',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ogretmenkayit',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
