# Generated by Django 3.1.4 on 2021-01-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0044_auto_20210102_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrencikayit',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
