# Generated by Django 3.1.4 on 2021-01-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0046_birebir_bbbitissaati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birebir',
            name='bbbitissaati',
        ),
        migrations.AlterField(
            model_name='ogretmenkayit',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
