# Generated by Django 3.1.4 on 2021-01-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0050_auto_20210103_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyurular',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
