# Generated by Django 3.1.4 on 2021-01-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0051_auto_20210103_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyurular',
            name='dogrenci',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='duyurular',
            name='dogretmen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='duyurular',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
