# Generated by Django 3.1.4 on 2021-01-02 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0052_auto_20210103_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyurular',
            name='dtarih',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 2, 20, 39, 999917), null=True),
        ),
    ]
