# Generated by Django 3.1.4 on 2021-01-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0053_auto_20210103_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duyurular',
            name='dtarih',
        ),
        migrations.AlterField(
            model_name='duyurular',
            name='duyuru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
