# Generated by Django 3.1.4 on 2021-01-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0055_duyurular_dtarih'),
    ]

    operations = [
        migrations.DeleteModel(
            name='duyurular',
        ),
    ]
