# Generated by Django 3.1.4 on 2021-01-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0056_delete_duyurular'),
    ]

    operations = [
        migrations.CreateModel(
            name='xxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gunler', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
