# Generated by Django 3.1.4 on 2021-01-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0057_xxx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xxx',
        ),
    ]
