# Generated by Django 3.1.4 on 2021-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0059_duyurular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyurular',
            name='dogrenci',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='duyurular',
            name='dogretmen',
            field=models.BooleanField(default=True),
        ),
    ]
