# Generated by Django 3.1.4 on 2021-01-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0062_auto_20210103_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='dersprogrami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dpsinif', models.CharField(blank=True, max_length=100, null=True)),
                ('dpogretmen', models.CharField(blank=True, max_length=100, null=True)),
                ('dpsaat', models.CharField(blank=True, max_length=10, null=True)),
                ('dpders', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='derssaatleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('baslamasaati', models.CharField(blank=True, max_length=10, null=True)),
                ('bitissaati', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
