# Generated by Django 3.1.4 on 2021-01-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0063_dersprogrami_derssaatleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='derssaatleri',
            name='derssirasi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
