# Generated by Django 3.1.4 on 2021-01-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0064_derssaatleri_derssirasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='derssaatleri',
            name='dersgurubu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
