# Generated by Django 3.1.4 on 2021-01-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0065_derssaatleri_dersgurubu'),
    ]

    operations = [
        migrations.CreateModel(
            name='dersguruplari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dersgurubu', models.CharField(blank=True, max_length=100, null=True)),
                ('aciklama', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dersprogrami',
            name='dersgurubu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
