# Generated by Django 3.1.4 on 2021-01-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0067_auto_20210104_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='birebir',
            name='bbbitissaati',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='birebir',
            name='bbsaati',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
