# Generated by Django 3.1.4 on 2021-01-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0068_auto_20210104_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kurum',
            new_name='kurums',
        ),
    ]
