# Generated by Django 3.1.4 on 2021-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0070_auto_20210109_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurums',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logom'),
        ),
    ]
