# Generated by Django 3.1.4 on 2021-01-11 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0071_auto_20210110_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='odeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('odogrenci', models.CharField(blank=True, max_length=100, null=True)),
                ('taksit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aciklama', models.CharField(blank=True, max_length=150, null=True)),
                ('odendi', models.BooleanField(default=False)),
                ('odemetarihi', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='taksitsayisi',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ogrencikayit',
            name='ucret',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
