# Generated by Django 3.1.4 on 2021-01-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0072_auto_20210112_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odeme',
            name='taksit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
