# Generated by Django 3.1.4 on 2021-01-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0073_auto_20210112_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogretmenkayit',
            name='muhasebe',
            field=models.BooleanField(default=False),
        ),
    ]
