# Generated by Django 3.1.4 on 2021-01-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilkapp', '0075_odeme_odemeyialan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrencikayit',
            name='ogrenciadres',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
